# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transactions.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x12\x0ctransactions\"/\n\x0cTopupRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"L\n\rTopupResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x02\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"0\n\rDeductRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"M\n\x0e\x44\x65\x64uctResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x02\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"$\n\x11GetBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"%\n\x12GetBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\x32\xec\x01\n\x12TransactionService\x12@\n\x05Topup\x12\x1a.transactions.TopupRequest\x1a\x1b.transactions.TopupResponse\x12\x43\n\x06\x44\x65\x64uct\x12\x1b.transactions.DeductRequest\x1a\x1c.transactions.DeductResponse\x12O\n\nGetBalance\x12\x1f.transactions.GetBalanceRequest\x1a .transactions.GetBalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPUPREQUEST']._serialized_start=36
  _globals['_TOPUPREQUEST']._serialized_end=83
  _globals['_TOPUPRESPONSE']._serialized_start=85
  _globals['_TOPUPRESPONSE']._serialized_end=161
  _globals['_DEDUCTREQUEST']._serialized_start=163
  _globals['_DEDUCTREQUEST']._serialized_end=211
  _globals['_DEDUCTRESPONSE']._serialized_start=213
  _globals['_DEDUCTRESPONSE']._serialized_end=290
  _globals['_GETBALANCEREQUEST']._serialized_start=292
  _globals['_GETBALANCEREQUEST']._serialized_end=328
  _globals['_GETBALANCERESPONSE']._serialized_start=330
  _globals['_GETBALANCERESPONSE']._serialized_end=367
  _globals['_TRANSACTIONSERVICE']._serialized_start=370
  _globals['_TRANSACTIONSERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
