# Generated by Django 5.0.4 on 2024-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDeveloperAssignmentApp', '0003_delete_person_alter_historicalperformance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transaction_Table',
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Vendor_Model',
        ),
    ]
